"""
Schema for the GRPI Working Agreement Generator.

Beckhard 1972 four-dimensional model of effective teams:

  G - Goals       - what is the team trying to achieve?
  R - Roles       - who owns what; who decides what
  P - Processes   - decision protocol, escalation path, abandonment criteria
  I - Interactions - communication norms, disagreement format

Unlike most AgentCity patterns (which are DIAGNOSTIC and consume a trace),
GRPI is GENERATIVE: it consumes a team-setup request and produces a
structured Working Agreement document.
"""

from __future__ import annotations

from datetime import datetime, timezone
from typing import Any

from pydantic import BaseModel, Field

DIMENSIONS: tuple[str, ...] = ("goals", "roles", "processes", "interactions")


def _utcnow() -> datetime:
    """Timezone-aware UTC now."""
    return datetime.now(timezone.utc)


# --- Input: team setup request ------------------------------------------


class AgentRole(BaseModel):
    """A named agent on the team with a short description.

    Optional fields let the requester pre-fill role detail; the generator
    will fill any gaps and enforce GRPI structure.
    """

    name: str
    description: str = ""
    decision_rights: list[str] = Field(default_factory=list)
    deliverables: list[str] = Field(default_factory=list)


class TeamSetupRequest(BaseModel):
    """A request to generate a GRPI Working Agreement for a new team."""

    team_id: str | None = None
    task: str
    agents: list[AgentRole]
    constraints: list[str] = Field(default_factory=list)
    success_criteria: list[str] = Field(default_factory=list)
    kill_criteria: list[str] = Field(default_factory=list)
    framework: str | None = None  # e.g. "crewai", "langgraph", "autogen"
    metadata: dict[str, Any] = Field(default_factory=dict)


# --- Output: GRPI Working Agreement ------------------------------------


class GoalsSection(BaseModel):
    """The Goals dimension of the working agreement."""

    primary_goal: str
    measurable_success_criteria: list[str]
    scope_boundaries: list[str] = Field(default_factory=list)
    deliverables: list[str] = Field(default_factory=list)
    kill_criteria: list[str] = Field(default_factory=list)


class RoleAssignment(BaseModel):
    """One agent's role inside the agreement."""

    agent_name: str
    role_title: str
    responsibilities: list[str]
    decision_rights: list[str]
    accountability_owner_for: list[str] = Field(
        default_factory=list,
        description="Workstreams this agent owns end-to-end accountability for.",
    )


class RolesSection(BaseModel):
    """The Roles dimension of the working agreement."""

    role_assignments: list[RoleAssignment]
    raci_summary: str = Field(
        default="",
        description="One-paragraph RACI-style summary of decision rights across the team.",
    )


class ProcessesSection(BaseModel):
    """The Processes dimension of the working agreement."""

    decision_protocol: str  # e.g. "consensus, fist-to-five, fallback to orchestrator"
    escalation_path: list[str]
    abandonment_criteria: list[str]
    communication_cadence: str
    review_cadence: str = ""
    artifact_storage: str = ""


class InteractionsSection(BaseModel):
    """The Interactions dimension of the working agreement."""

    disagreement_norms: list[str]
    feedback_format: str  # e.g. "plus/delta", "SBI", "free-form"
    conflict_resolution: str
    voice_and_turn_taking: list[str] = Field(default_factory=list)
    psychological_safety_commitments: list[str] = Field(default_factory=list)


class WorkingAgreement(BaseModel):
    """The full GRPI Working Agreement output."""

    team_id: str | None = None
    task: str
    goals: GoalsSection
    roles: RolesSection
    processes: ProcessesSection
    interactions: InteractionsSection

    # Metadata
    generated_at: datetime = Field(default_factory=_utcnow)
    generator_model: str | None = None
    framework: str | None = None

    def to_markdown(self) -> str:
        """Render the agreement as a markdown document suitable for storage
        in a team's shared docs, an orchestrator prompt, or an audit log.
        """
        out: list[str] = []
        out.append("# Working Agreement (GRPI)\n")
        out.append(f"_Generated {self.generated_at.isoformat()}_\n")
        if self.team_id:
            out.append(f"_Team: {self.team_id}_\n")
        if self.framework:
            out.append(f"_Framework: {self.framework}_\n")
        if self.generator_model:
            out.append(f"_Generated by: {self.generator_model}_\n")

        out.append(f"\n## Task\n\n{self.task}\n")

        out.append("\n## G — Goals\n\n")
        out.append(f"**Primary goal:** {self.goals.primary_goal}\n\n")
        out.append("**Measurable success criteria:**\n")
        for c in self.goals.measurable_success_criteria:
            out.append(f"- {c}\n")
        if self.goals.deliverables:
            out.append("\n**Deliverables:**\n")
            for d in self.goals.deliverables:
                out.append(f"- {d}\n")
        if self.goals.scope_boundaries:
            out.append("\n**Scope boundaries:**\n")
            for b in self.goals.scope_boundaries:
                out.append(f"- {b}\n")
        if self.goals.kill_criteria:
            out.append("\n**Kill criteria:**\n")
            for k in self.goals.kill_criteria:
                out.append(f"- {k}\n")

        out.append("\n## R — Roles\n")
        for ra in self.roles.role_assignments:
            out.append(f"\n### {ra.agent_name} — {ra.role_title}\n")
            out.append("**Responsibilities:**\n")
            for r in ra.responsibilities:
                out.append(f"- {r}\n")
            out.append("\n**Decision rights:**\n")
            for d in ra.decision_rights:
                out.append(f"- {d}\n")
            if ra.accountability_owner_for:
                out.append("\n**Owns end-to-end:**\n")
                for o in ra.accountability_owner_for:
                    out.append(f"- {o}\n")
        if self.roles.raci_summary:
            out.append(f"\n**RACI summary:** {self.roles.raci_summary}\n")

        out.append("\n## P — Processes\n\n")
        out.append(f"**Decision protocol:** {self.processes.decision_protocol}\n\n")
        out.append("**Escalation path:**\n")
        for step in self.processes.escalation_path:
            out.append(f"- {step}\n")
        out.append("\n**Abandonment criteria:**\n")
        for c in self.processes.abandonment_criteria:
            out.append(f"- {c}\n")
        out.append(f"\n**Communication cadence:** {self.processes.communication_cadence}\n")
        if self.processes.review_cadence:
            out.append(f"\n**Review cadence:** {self.processes.review_cadence}\n")
        if self.processes.artifact_storage:
            out.append(f"\n**Artifact storage:** {self.processes.artifact_storage}\n")

        out.append("\n## I — Interactions\n\n")
        out.append("**Disagreement norms:**\n")
        for n in self.interactions.disagreement_norms:
            out.append(f"- {n}\n")
        out.append(f"\n**Feedback format:** {self.interactions.feedback_format}\n")
        out.append(f"\n**Conflict resolution:** {self.interactions.conflict_resolution}\n")
        if self.interactions.voice_and_turn_taking:
            out.append("\n**Voice & turn-taking:**\n")
            for v in self.interactions.voice_and_turn_taking:
                out.append(f"- {v}\n")
        if self.interactions.psychological_safety_commitments:
            out.append("\n**Psychological-safety commitments:**\n")
            for ps in self.interactions.psychological_safety_commitments:
                out.append(f"- {ps}\n")

        return "".join(out)

    def to_orchestrator_preamble(self) -> str:
        """Render a condensed text block suitable for prepending to an
        orchestrator's system prompt at runtime.
        """
        lines = [
            "TEAM WORKING AGREEMENT (GRPI):",
            f"Task: {self.task}",
            "",
            "Goals:",
            f"- Primary: {self.goals.primary_goal}",
            f"- Success criteria: {'; '.join(self.goals.measurable_success_criteria)}",
            "",
            "Roles:",
        ]
        for ra in self.roles.role_assignments:
            lines.append(f"- {ra.agent_name}: {ra.role_title}")
        lines.extend(
            [
                "",
                f"Decision protocol: {self.processes.decision_protocol}",
                f"Escalation path: {' -> '.join(self.processes.escalation_path)}",
                f"Communication: {self.processes.communication_cadence}",
                "",
                f"Disagreement norms: {'; '.join(self.interactions.disagreement_norms)}",
                f"Feedback format: {self.interactions.feedback_format}",
            ]
        )
        return "\n".join(lines)
