"""``vstack-hello`` CLI.

Runs an end-to-end synthetic AAR so a new user can see vstack work in
under 30 seconds, with no manual trace construction. Falls back to a
pre-rendered sample if no LLM client is reachable.
"""

from __future__ import annotations

import argparse
import json
import sys
from typing import Sequence

from ._hello import run_hello


_BANNER = (
    "================================================================\n"
    " vstack hello — first-run smoke test\n"
    " Organizational behavior, practiced on AI agents.\n"
    "================================================================\n"
)

_FOOTER_TEMPLATE = """\
================================================================
What you just saw
================================================================

A 7-step synthetic agent trace was fed into vstack's After-Action
Review pattern (#30 of 34). The output above is the AAR — Wharton's
4-step debrief framework applied to an AI agent run instead of a
military operation or a corporate post-mortem.

vstack ships 33 more diagnostic patterns, each anchored in named
organizational-behavior literature. They share a common LLM-client
core, run on any agent framework, and ship as Python imports, CLIs,
an MCP server, a REST API, framework adapters, and a Docker image.

Try next:
  vstack-doctor                       # full install diagnostic
  vstack-lewin --help                 # individual-behavior pattern
  vstack-lencioni --help              # team-dynamics pattern
  vstack-mcp serve                    # MCP server for Claude Desktop /
                                      # Cursor / Cline / Continue / etc.
  vstack-api serve                    # REST API (FastAPI)
  vstack --help                       # this trace's pattern (AAR)

Docs:
  https://valani9.github.io/vstack/   # docs site
  https://github.com/valani9/vstack   # source + 34 pattern READMEs
"""


def main(argv: Sequence[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        prog="vstack-hello",
        description=(
            "Run a 30-second smoke test that proves your vstack install "
            "works end-to-end. Builds a synthetic agent trace and feeds "
            "it through the After-Action Review pattern. If an LLM API "
            "key (ANTHROPIC_API_KEY / OPENAI_API_KEY / OLLAMA_HOST) is "
            "set, runs a real AAR; otherwise prints a pre-rendered "
            "sample so you can still see the shape of the output."
        ),
    )
    parser.add_argument(
        "--offline",
        action="store_true",
        help=(
            "Skip LLM resolution and always print the pre-rendered "
            "sample AAR. Useful for CI smoke tests and demo recordings."
        ),
    )
    parser.add_argument(
        "--json",
        dest="as_json",
        action="store_true",
        help="Emit a machine-readable JSON envelope instead of pretty text.",
    )
    parser.add_argument(
        "--no-banner",
        action="store_true",
        help="Skip the ASCII banner and footer (useful when piping output).",
    )
    args = parser.parse_args(argv)

    result = run_hello(force_offline=args.offline)

    if args.as_json:
        body = {
            "resolution": {
                "status": result.resolution.status.value,
                "label": result.resolution.label,
                "hint": result.resolution.hint,
            },
            "used_real_llm": result.used_real_llm,
            "elapsed_seconds": result.elapsed_seconds,
            "trace": {
                "agent_id": result.trace.agent_id,
                "agent_framework": result.trace.agent_framework,
                "goal": result.trace.goal,
                "step_count": len(result.trace.steps),
                "success": result.trace.success,
                "outcome": result.trace.outcome,
            },
            "aar_markdown": result.aar_markdown,
            "notes": result.notes,
        }
        print(json.dumps(body, indent=2))
        return 0

    out = sys.stdout
    if not args.no_banner:
        out.write(_BANNER + "\n")

    out.write(f"LLM client: {result.resolution.label}\n")
    if result.resolution.hint:
        out.write(f"  hint: {result.resolution.hint}\n")
    out.write("\n")

    out.write(
        f"Sample trace: agent_id={result.trace.agent_id!r}, "
        f"{len(result.trace.steps)} steps, "
        f"success={result.trace.success}\n"
    )
    out.write(f"  goal:    {result.trace.goal}\n")
    out.write(f"  outcome: {result.trace.outcome}\n\n")

    if result.used_real_llm:
        elapsed = (
            f" (took {result.elapsed_seconds:.1f}s)" if result.elapsed_seconds is not None else ""
        )
        out.write(f"Generated by a real LLM call to {result.resolution.status.value}{elapsed}.\n\n")
    else:
        out.write("Showing the pre-rendered sample AAR (no LLM call made).\n\n")

    out.write("================================================================\n")
    out.write("After-Action Review (Wharton 4-step)\n")
    out.write("================================================================\n\n")
    out.write(result.aar_markdown)
    if not result.aar_markdown.endswith("\n"):
        out.write("\n")

    for note in result.notes:
        out.write(f"\nNote: {note}\n")

    if not args.no_banner:
        out.write("\n" + _FOOTER_TEMPLATE)

    return 0


if __name__ == "__main__":
    sys.exit(main())
